entries: add new SppeedP and Hover Defender homebrew
gbdev/database pull request #234
Opened 2024-03-25 17:15 UTC by kldobrev

Added new entries

2024-03-25 18:27 UTC, avivace commented
Can you correct Sport -> Sports ?

2024-03-25 18:28 UTC, avivace requested changes

2024-03-25 18:28 UTC, avivace commented on entries/speedp/game.json
> +        "Sport"
```suggestion
        "Sports"
```

2024-03-25 19:33 UTC, kldobrev commented
The tag is updated.

2024-03-25 21:35 UTC, avivace approved these changes

2024-03-26 00:13 UTC, merged

2024-03-27 21:11 UTC, kldobrev commented
Hello and thank you for merging my commit. 
After adding the last 2 entries to the database, I tried searching for them in the Homebrew Hub, but I did not get any results. 
I read in the description that the changes should propagate automatically to it. 
Is there something else I need to do to make these entries visible?
Please advise.

2024-03-29 09:15 UTC, avivace commented
> Hello and thank you for merging my commit. After adding the last 2 entries to the database, I tried searching for them in the Homebrew Hub, but I did not get any results. I read in the description that the changes should propagate automatically to it. Is there something else I need to do to make these entries visible? Please advise.

Hey @kldobrev ! Nothing needed from you're side, I'll trigger a re-deployment in the next few days ;)